### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by krviolent** [tonlabs/ton-labs-node#1]
I am getting this error while building:
   Compiling ton_api v0.0.1 (https://github.com/tonlabs/ton-labs-tl.git#8117a829)
error: failed to run custom build command for `ton_api v0.0.1 (https://github.com/tonlabs/ton-labs-tl.git#8117a829)`

Caused by:
  process didn't exit successfully: `/mnt/f/DATA/Documents/Work/ton-labs-node/target/release/build/ton_api-e235b54108fe1794/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/ton
cargo:rerun-if-changed=tl
cargo:rerun-if-changed=../ton_tl_codegen
cargo:rerun-if-changed=tl/lite_api.tl
cargo:rerun-if-changed=tl/ton_api.tl
cargo:rerun-if-changed=tl/ton_net.tl
cargo:rerun-if-changed=tl/tonlib_api.tl

**Comment by DezzK** [comment]
It can be fixed by installing rustfmt component:
`rustup component add rustfmt`
