### ISSUE TITLE
No way to connect to the node via remote console

### ISSUE THREAD

**Issue by serge-medvedev** [tonlabs/ton-labs-node#57]
`self.control_server` [contains](https://github.com/tonlabs/ton-labs-node/blob/a49434318f80138c76fef299e24ab718f0877602/src/config.rs#L239) hard-coded `LOCAL_HOST` address which makes it impossible to connect to the `control_server_port` from addresses other than 127.0.0.1.

**Comment by artemr-tl** [comment]
node console works locally only now.

**Comment by serge-medvedev** [comment]
> node console works locally only now.

Is it gonna be fixed? `lite-client` works remotely without an issue and there's a perfect logic in it, isn't there?

**Comment by yaroslavser** [comment]
This behavior is only for initialization. You can modify IP address in console config with real address of node.
Issue can be closed.
