### ISSUE TITLE
Wrong (hardcoded) path of part of db

### ISSUE THREAD

**Issue by Custler** [tonlabs/ton-labs-node#81]
You hardcoded part of database to /node_db

```
in validator_group.rs (164) let db_root = "node_db/catchains".to_string();
in validator_group.rs (222) ("node_db/candidates/{}", session_id.to_hex_string()))
in validator_manager.rs (258) new("node_db/last_rotation_block".to_string())
```
and may be somewhere else 

It has to be corrected and placed to the db folder as all other parts of the db, according to "internal_db_path":  in default_config.json file

**Comment by SkySonR** [comment]
It's very important thing. It can be one of the reasons why in rustnet we have nodes which does not sign blocks. If run service as non-root it will be able to sync and send request to elector, but can't sign any blocks. Please change it ASAP or add requirements that Rustnode can work only by root user.

**Comment by EvgueniGavrilov** [comment]
> It's very important thing. It can be one of the reasons why in rustnet we have nodes which does not sign blocks. If run service as non-root it will be able to sync and send request to elector, but can't sign any blocks. Please change it ASAP or add requirements that Rustnode can work only by root user.

actually, the node can run with non-root user, but the relative path hardcoding makes node functional while starting it from top-level DB directory ONLY.

Weird enough, of course. I suppose it would be better to use absolute path in config.
