### ISSUE TITLE
Doesn't work after update

### ISSUE THREAD

**Issue by 0xdeafbeef** [tonlabs/ton-labs-node#9]
thread 'tokio-runtime-worker' panicked at 'Block handles seq_no must be written in ascending order!', /data/node/.cargo/git/checkouts/ton-labs-node-storage-1efe65d4a9df40ac/1db33bf/src/block_index_db.rs:203:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR src/sync.rs:37 [sync] 139963162424192: Error while downloading and applying package: panic
thread 'tokio-runtime-worker' panicked at 'Poisoned RwLock: "PoisonError { inner: .. }"', /data/node/.cargo/git/checkouts/ton-labs-node-storage-1efe65d4a9df40ac/1db33bf/src/block_index_db.rs:201:14

**Comment by DezzK** [comment]
Thank you for your report. Sorry for not looking into it immediately. It is already fixed in the private repo and needs some time to be merged into the master of the public repo.
